### ISSUE TITLE
Use <route> tags to register apps without using layout?

### ISSUE THREAD

**Issue by MV10** [react-microfrontends/root-config#23]
I need a recommendation:

One of the things I like about this demo project is how `react-mf-root-config.js` generates the app registration from the `<route>` tags in the layout template. I suppose this is hard-coding either way, but it strikes me as easier to read, and as others on my team are learning the ropes, I'm seeing that it makes more sense to anyone who is accustomed to this style of route declaration.

I'm trying to work out the best way to do the same thing without the use of layout, though. The off-the-shelf non-layout root-config project is pretty bare-bones.

Or alternately, maybe it makes more sense to use layout with a "flat" structure to take advantage of the construct methods, rather than re-inventing the wheel? I see that `constructRoutes` in layout is pretty involved...

**Comment by internettrans** [comment]
single-spa-layout uses `pathToActiveWhen` to generate activity functions for the routes. Here's some documentation that might be helpful:

https://single-spa.js.org/docs/api#pathtoactivewhen
https://single-spa.js.org/docs/api#configuration-object
https://single-spa.js.org/docs/configuration#activity-function

We suggest using single-spa-layout, as there aren't really any downsides to doing so. Attempting to get the same functionality as single-spa-layout without using it will result in just a reimplementation of what already exists. The `constructRoutes` API is not extremely complex. However, if it has deterred you from using single-spa-layout and you'd like to reimplement the functionality that exists within single-spa-layout, here is how you could:

When not using single-spa-layout, generally routes are defined per application. If you'd like the inverse (defining the applications for each route), you could try something like this. I'm writing this code without having tested it, so there are no guarantees it works as-is:

```js
const routes = {
  "/": ["@org/navbar"]
  "/clients": ["@org/client-list", "@org/sidebar"],
}

registerApplication({
  name: "@org/navbar",
  app: () => System.import("@org/navbar"),
  activeWhen: routesToActiveWhen("@org/navbar")
})

registerApplication({
  name: "@org/client-list",
  app: () => System.import("@org/client-list"),
  activeWhen: routesToActiveWhen("@org/client-list")
})

registerApplication({
  name: "@org/sidebar",
  app: () => System.import("@org/sidebar"),
  activeWhen: routesToActiveWhen("@org/sidebar")
})

function routesToActiveWhen(appName) {
  return Object.keys(routes).filter(route => routes[route].includes(appName);
}
```
