### ISSUE TITLE
子应用怎么加载到父应用对应位置处

### ISSUE THREAD

**Issue by Jarryxin** [react-microfrontends/root-config#25]
![image](https://user-images.githubusercontent.com/21277570/118230257-f2314300-b4bf-11eb-8a72-95bc3f70d431.png)
红色箭头代表的是主+子应用，蓝色箭头代表想把子应用渲染到主应用的位置

**Comment by internettrans** [comment]
Duplicate of https://github.com/polyglot-microfrontends/account-settings/issues/10
