### ISSUE TITLE
root-config able to run on local development only, failed to load @[org-name]/root-config build on IIS Windows server

### ISSUE THREAD

**Issue by syaifuri** [react-microfrontends/root-config#26]
Hello, please help, i just explore the single-spa.

i want to create an intranet application with root- container with multiple parcel applications with all dependency cdn (js files) was stored on local intranet server.
On the local development root-config, it is running well to call and display multiple single-spa parcel from different host. 
but i got issue on build productive windows server environment (IIS).
- Unhandled Promise rejection: Unable to resolve bare specifier "@ifx/root-config" 

Do implement importmap.json stored on local IIS host server and bypass local check (without importmap.json - inline import), both method failed on build productive Error : Error: Unable to resolve bare specifier "@ifx/root-config" . but it is running well on the local development method, single-spa able to load properly for inline import or importmap.json concept.

**Comment by internettrans** [comment]
> Unable to resolve bare specifier "@ifx/root-config"

This means that your import map failed to load or does not contain `@ifx/root-config`. You can check the Network tab of the browser devtools and verify that the request is correct. Look for `<script type="systemjs-importmap" src="/importmap.json"></script>` in your root config index.ejs to find the URL for the import map. A common reason that import maps fail to load is if the server hosting them does not have CORS enabled to send an `Access-Control-Allow-Origin` header.

> i want to create an intranet application with root- container with multiple parcel applications with all dependency cdn (js files) was stored on local intranet server.

See https://github.com/single-spa/self-hosted-shared-dependencies

**Comment by syaifuri** [comment]
Thanks for the reply.
after did some configuration on IIS, the error of loading root-config is success, but i got another issue with loading  all applications, with error: 
#37: Invalid application - no unmount function ( Uncaught Error: application '@ifx/appname' died in status LOADING_SOURCE_CODE: undefined )
the problem is, within local environment, the localhost:9000 able to load all applications without issue, but within IIS, all application is still failed to load, 
BTW, this is my code for modified root-config.ts
`
import { registerApplication, start } from "single-spa";
import {
  constructApplications,
  constructRoutes,
  constructLayoutEngine,
} from "single-spa-layout";
import microfrontendLayout from "./microfrontend-layout.html";

const routes = constructRoutes(microfrontendLayout);
const applications = constructApplications({
  routes,
  loadApp({ name }) {
    return System.import(name);
  },
});
const layoutEngine = constructLayoutEngine({ routes, applications });

// Element ID "Empty Info"
document.getElementById("emptyinfo").hidden = true;
const queryString = window.location.search
const urlParams = new URLSearchParams(queryString);
const hostpc = urlParams.get('hostpc')

// Function Rest API
// API URL
async function getEquipment() {
  let response = await fetch('http://localwebapi.com:8000/OPUIAPI/API/GetInitialData?hostName='+ hostpc)
  let data = await response.json()
  console.log(data);
  return data;
}


//Call API to get mapping
getEquipment()
  .then(function(data) {
  // check equipment id
    let data0 = data[0];
    console.log(data0);
    let equipmentName = data0['equipmentName'];
    console.log(equipmentName)
    if(equipmentName != undefined) 
    {
      registerapps(equipmentName); 
    }
    else
    {
      document.getElementById("emptyinfo").hidden = false;
    }       

  })
  .catch(function(error) {
    console.log(error);
    document.getElementById("emptyinfo").hidden = false;
});
    


function registerapps(eqid) {
  //Register Applications into MappingLayout

  registerApplication({
    name: "@ifx/logdata",
    app: () => System.import("@ifx/logdata"),
    activeWhen: ["/"],
    customProps: { equipmentId: eqid},
  });

  registerApplication({
    name: "@ifx/metadata",
    app: () => System.import("@ifx/metadata"),
    activeWhen: ["/"],
    customProps: { equipmentId: eqid},
  });

  registerApplication({
    name: "@loadnGo",
    app: () => System.import("@loadnGo"),
    activeWhen: ["/"],
    customProps: { equipmentId: eqid},
  });

}

layoutEngine.activate();
start();
`

thanks

**Comment by internettrans** [comment]
The code you shared is not enough to diagnose the problem - please provide a demonstration of the issue, with instructions on how to reproduce the problem.

**Comment by syaifuri** [comment]
Hi Joeldenning,

this is my repository for example code : [Git-Single-Spa](https://github.com/syaifuri/Root-config-single-spa).
finally i do fix my issue after testing all dependency of js i.e. single-spa.min.js, system.js at index.ejs from localweb IIS server path returned it back into cdn path --> https://cdn.jsdelivr.net/xxx. and do reverse testing using local path or cdn to find which js file reference that make the issue of loading application.

no idea what's wrong with the local path references loading if we put on productive environment, all local js was copied and accessible and run smoothly with localhost:9000.

after do some testing the actual issue is due to system.js and amd.js references.
if i do revert into cdn path, the issue was resolved, all application can load successfully.
if the path reference of system.js & amd.js refer into local web IIS server path, the issue will be happened.

so my temporary solution now, is all path for system.js & amd.js uses cdn path https://cdn.jsdelivr.net/npm/systemjs@6.8.3/dist/xxxx

**Comment by internettrans** [comment]
I cloned the repo but it seems this is only reproducible on a windows server? Is it possible to reproduce on normal Windows laptop?

**Comment by syaifuri** [comment]
Hi,
the issue is on windows server. let me reproduce it on normal windows laptop with create all dependency js into local PC. will update the result.

**Comment by syaifuri** [comment]
Do test on local PC using IIS, with the all path refer to local , everything is fine.

![localpath_Js](https://user-images.githubusercontent.com/1688962/125165944-5ff9a280-e1c3-11eb-95b0-c8f640b06809.JPG)

![importmap_json](https://user-images.githubusercontent.com/1688962/125165935-54a67700-e1c3-11eb-8e6b-fdb1d1d8a30d.JPG)

confirmed, something wrong with server configuration (possible security setting) on using ./system.min.js as local path reference, only cdn path can works. 

Because it's able to run on IIS on local PC,  **there is no issue on single-spa.**
