### ISSUE TITLE
"templateParameters.isLocal" in webpack.config.js  seems invalid

### ISSUE THREAD

**Issue by Demian1996** [react-microfrontends/root-config#27]
webpack.config.js
```js
templateParameters: {
  isLocal: webpackConfigEnv && webpackConfigEnv.isLocal === "true",
  orgName,
},
```

package.json
```shell
webpack serve --port 9000 --env isLocal
```

When I run `yarn start`，I find that ejs was not loading a local js file.
I printed the following in the webpack.config.js file
```js
console.log(webpackConfigEnv, webpackConfigEnv.isLocal === "true");
```
result is
```js
{ WEBPACK_SERVE: true, isLocal: true } false
```

**Comment by internettrans** [comment]
This was fixed in create-single-spa at https://github.com/single-spa/create-single-spa/pull/251 for newly generated projects. This project was generated before it, though. So I've fixed this project in 6573a82
