### ISSUE TITLE
Testing problem with System.import

### ISSUE THREAD

**Issue by Jonnybravo** [react-microfrontends/root-config#28]
Hi,

I'm trying to make this example to work: https://single-spa.js.org/docs/testing/units/#jest-config, but I always get an error on System when I'm trying to do this.

Here are the steps that I did:

- On the planets project added the following files/code:
```
// jest.config.js
module.exports = {
  collectCoverageFrom: ["src/**/*.js"],
  modulePathIgnorePatterns: ["/cache", "/dist"],
  transform: {
    "^.+\\.(j|t)sx?$": "babel-jest",
  },
  setupFilesAfterEnv: ["<rootDir>/jest.setup.js"],
  moduleNameMapper: {
    // Note this is only needed if you don't match the module name directly
    // an alternative would be to place the mock in
    // <rootDir>/__mocks__/@react-mf/styleguide.js and it would be autodetected
    "@react-mf/styleguide": "<rootDir>/__mocks__/react-mf-styleguide.js",
    "@react-mf/people": "<rootDir>/__mocks__/people/react-mf-people.js",
  },
};
```
```
// jest.setup.js
// import Mocks for SystemJS mock below
import peopleApplication from "@react-mf/people";
// Mock SystemJS
global.System = {
  import: jest.fn(mockImport),
};

function mockImport(importName) {
  // What you do in mock import will depend a lot on how you use SystemJS in the project and components you wish to test

  /* If I had already created a mock for `@react-mf/people` and I wanted to test this component:
   *  https://github.com/react-microfrontends/planets/blob/main/src/planets-page/selected-planet/selected-planet.component.js#L5
   * I would want `System.import('@react-mf/people')` to resovle to my mock one way to accomplish this would be the following
   */
  if (importName === "@react-mf/people") {
    return Promise.resolve(peopleApplication);
  } else {
    console.warn("No mock module found");
    return Promise.resolve({});
  }
}

```
- Next, I built a version of `@react-mf/people` and put if on the folder` /__mocks__/people/react-mf-people.js`

When I try to run an unrelated test, I got an error on the System. 

![image](https://user-images.githubusercontent.com/1081108/127890104-658ce9f6-39de-4990-b067-684b53444c27.png)

What am I doing wrong here? Is it possible for you to implement the example described in the documentation?

Thanks

**Comment by Jonnybravo** [comment]
I tried to do something more simple, just a quick test to check if I could use a component that imports something from `@react-mf/styleguide`.

1. Made a build of  `@react-mf/styleguide` and put it on `/__mocks__/@react-mf/styleguide.js`. As explained on the comment on `jest.config.js`, the import was autodetected.
2. Removed the `moduleNameMapper` and `jest.setup.js` as I don't need them for this quick test.
3. Created the following test for the `planets-page.component`
```
// planets-page.test.js
import PlanetPage from "./planets-page.component";
import React from "react";
import renderer from "react-test-renderer";

describe("selected-planet", () => {
  it("should render the page", () => {
    debugger;
    const tree = renderer.create(<PlanetPage />).toJSON();
    expect(tree).toMatchSnapshot();
  });
});
```

The error is still the same. You can check it below:

![image](https://user-images.githubusercontent.com/1081108/127894757-1e20f693-5989-4b39-a185-09ea5f501f3c.png)

**Comment by internettrans** [comment]
I wouldn't recommend loading SystemJS modules in tests. Instead, load ESM or CJS modules in tests.
