### ISSUE TITLE
Live example not working

### ISSUE THREAD

**Issue by Dannymx** [react-microfrontends/root-config#43]
The live example at this url https://react.microfrontends.app is not working

Someone forgot to pay the server bill?

**Comment by jshike** [comment]
bump! still down, for all example website.

**Comment by caporale-edilportale** [comment]
Also the import map in index.ejs is loaded from "https://storage.googleapis.com/vue.microfrontends.app/importmap.json" which is also not working due to a closed account.

**Comment by HomiG** [comment]
Is there a workaround to find this file?

**Comment by HomiG** [comment]
> s

Is there a workaround to find this file?

**Comment by HomiG** [comment]
> Also the import map in index.ejs is loaded from "https://storage.googleapis.com/vue.microfrontends.app/importmap.json" which is also not working due to a closed account.

Is there a workaround to find this file?

**Comment by internettrans** [comment]
Fixed
